### ISSUE TITLE
Setting up on apache

### ISSUE THREAD

**Issue by amenk** [biodranik/Alohalytics#53]
I am trying to set up the server behind apache. I guess I have eto use mod_proxy_fcgi for this and start the Alohalytics server in the background to listen on port 8888 (when I have a look at the NGINX example).

But the server just immediately quits - is that normal?

    /srv/alohalytics/bin# ./fcgi_server ../data/ /monitoring
    24/Jul/2018:20:16:10 Alohalytics: FastCGI Server instance is ready to serve clients' requests.
    24/Jul/2018:20:16:10 Alohalytics: Shutting down FastCGI server instance.

I am actually using maps.me 's fork...

**Comment by biodranik** [comment]
Apache should spawn fcgi binary server automatically, I didn’t try it though. Have you checked some online tutorials?

**Comment by biodranik** [comment]
Have you tried something like this tutorial? http://bigbang.waterlin.org/bang/using-apache-with-cpp-to-develop-fastcgi-web-server/

The idea is that you have a directory in apache config with your binary, and apache spawns/calls it automatically for all requests to http://url/binary_name_from_this_directory

**Comment by biodranik** [comment]
Most old tutorials are written for Apache 2.2, not for 2.4. There is one significant difference in apache2.4 config (for directory permissions): https://httpd.apache.org/docs/2.4/upgrading.html

**Comment by amenk** [comment]
I think my setup is similar, but I have index.fcgi like this, because I have to pass params to Alohalytics:

    #!/bin/sh

    exec /var/www/alohalytics/bin/fcgi_server /var/www/alohalytics/data /monitoring     /var/www/alohalytics/logs/error.log

No I am getting in the /var/www/alohalytics/logs/error.log

24/Jul/2018:21:37:41 Alohalytics: WARNING: Request is ignored due to invalid or missing Content-Length header <NULL> 197.156.86.154 /android/com.addismap.me/829 Dalvik/2.1.0 (Linux; U; Android 7.1.1; E5823 Build/32.4.A.1.54)

**Comment by amenk** [comment]
I got it working!

            FcgidPassHeader Content-Length

**Comment by biodranik** [comment]
Great! Thanks for sharing working solution 👍
